

/* EMPLOYEE ANNUAL LEAVE ACCURAL REPORT */

WITH ANNUAL AS
(SELECT 	 APAE.END_BAL ANU_BAL
			,APAE.PERSON_ID
			,APAE.PLAN_ID
            ,APAE.BEGIN_BAL CFW
			,APAE.ACCRUED CURRENT_YEAR_ACC_BAL	
            ,APAE.ACCRUAL_PERIOD			
	FROM 
	 ANC_PER_ACCRUAL_ENTRIES APAE
	,ANC_ABSENCE_PLANS_VL AAPV
  WHERE APAE.PLAN_ID = AAPV.ABSENCE_PLAN_ID(+)
  AND UPPER(AAPV.NAME) = 'ANNUAL LEAVE'
  AND APAE.ACCRUAL_PERIOD  =(SELECT MAX (APA.ACCRUAL_PERIOD)
                           FROM ANC_PER_ACCRUAL_ENTRIES APA
                           WHERE APAE.PERSON_ID = APA.PERSON_ID
                           AND APA.PLAN_ID  = APAE.PLAN_ID
						   
						   AND TO_CHAR(APA.ACCRUAL_PERIOD,'YYYY') <= TO_CHAR(SYSDATE,'YYYY')
                           )
						   )
,ADJUSYMENT AS
(SELECT 
APAED1.PERSON_ID,
NVL(F.MEANING,'ADJUSTMENT') ADJUSTMENT_REASON,
SUM(APAED1.VALUE) ADJUSMENTS

FROM
ANC_PER_ACRL_ENTRY_DTLS APAED1,
ANC_ABSENCE_PLANS_VL      AAPV,
HCM_LOOKUPS F
WHERE 1=1
AND APAED1.TYPE = 'ADJOTH'
-- AND APAED1.SOURCE = 'ANC'
AND APAED1.VOIDED_ACRL <> 'Y'
AND APAED1.ADJUSTMENT_REASON		=F.LOOKUP_CODE(+)
AND APAED1.PL_ID 				  	= AAPV.ABSENCE_PLAN_ID
AND TRUNC(SYSDATE) BETWEEN TRUNC(AAPV.EFFECTIVE_START_DATE) AND TRUNC(AAPV.EFFECTIVE_END_DATE)
AND UPPER(AAPV.NAME)			IN ('ANNUAL LEAVE')
AND F.LOOKUP_TYPE(+)='ANC_ABS_PLAN_OTHER_REASONS'
GROUP BY
APAED1.PERSON_ID,
F.MEANING
)
,ABSENCE_DETAILS AS
(SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION ,
			AATV.NAME
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND UPPER(AATV.NAME)        ='ANNUAL LEAVE'
			AND TRUNC(SYSDATE) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
		    -- AND (TO_CHAR(SYSDATE,'DD-MM-YYYY') IN (:P_PERIOD) OR 'ALL' IN((:P_PERIOD) || 'ALL'))
-- AND APAE.PERSON_ID ='300000004032508'
		GROUP BY APAE.PERSON_ID,
		AATV.NAME
		)
		
,LAST_TWO_YEAR AS
(
SELECT 	 APAE.END_BAL ANU_BAL
			,APAE.PERSON_ID
			,APAE.PLAN_ID
            ,APAE.BEGIN_BAL CFW
			,APAE.ACCRUED CURRENT_YEAR_ACC_BAL	
            ,APAE.ACCRUAL_PERIOD			
	FROM 
	 ANC_PER_ACCRUAL_ENTRIES APAE
	,ANC_ABSENCE_PLANS_VL AAPV
  WHERE APAE.PLAN_ID = AAPV.ABSENCE_PLAN_ID(+)
  AND UPPER(AAPV.NAME) = 'ANNUAL LEAVE'
  AND APAE.ACCRUAL_PERIOD  =(SELECT MAX (APA.ACCRUAL_PERIOD)
                           FROM ANC_PER_ACCRUAL_ENTRIES APA
                           WHERE APAE.PERSON_ID = APA.PERSON_ID
                           AND APA.PLAN_ID  = APAE.PLAN_ID
						   
						   AND TO_CHAR(APA.ACCRUAL_PERIOD,'YYYY') <= TO_CHAR(SYSDATE,'YYYY')-2
                           )
)
,LAST_YEAR AS
(
SELECT 	 APAE.END_BAL ANU_BAL
			,APAE.PERSON_ID
			,APAE.PLAN_ID
            ,APAE.BEGIN_BAL CFW
			,APAE.ACCRUED CURRENT_YEAR_ACC_BAL	
            ,APAE.ACCRUAL_PERIOD			
	FROM 
	 ANC_PER_ACCRUAL_ENTRIES APAE
	,ANC_ABSENCE_PLANS_VL AAPV
  WHERE APAE.PLAN_ID = AAPV.ABSENCE_PLAN_ID(+)
  AND UPPER(AAPV.NAME) = 'ANNUAL LEAVE'
  AND APAE.ACCRUAL_PERIOD  =(SELECT MAX (APA.ACCRUAL_PERIOD)
                           FROM ANC_PER_ACCRUAL_ENTRIES APA
                           WHERE APAE.PERSON_ID = APA.PERSON_ID
                           AND APA.PLAN_ID  = APAE.PLAN_ID
						   
						   AND TO_CHAR(APA.ACCRUAL_PERIOD,'YYYY') <= TO_CHAR(SYSDATE,'YYYY')-1
                           )
)						   
		
SELECT
-- PAPF.PERSON_ID
PAPF.PERSON_NUMBER EMPLOYEE_NUMBER
,PPNF.LAST_NAME||','||PPNF.TITLE||' '||PPNF.FIRST_NAME||' '||PPNF.MIDDLE_NAMES||' '||PPNF.NAM_INFORMATION1 AS EMPLOYEE_NAME
,(SELECT
  HAOU1.NAME
  FROM
   HR_ALL_ORGANIZATION_UNITS HAOU1
  ,PER_ORG_TREE_NODE POTN
   WHERE
   1 = 1
   AND POTN.TREE_CODE = 'OWWSC_ORG_TREE'
   AND HAOU1.ORGANIZATION_ID = POTN.PARENT_PK1_VALUE
   AND HAOU1.ATTRIBUTE2 = 'DIVISION'
   AND ROWNUM = 1 START WITH POTN.PK1_START_VALUE = HAOUF.ORGANIZATION_ID CONNECT BY PRIOR POTN.PARENT_PK1_VALUE = POTN.PK1_START_VALUE) DIVISION
,(SELECT
  HAOU1.NAME
  FROM
   HR_ALL_ORGANIZATION_UNITS HAOU1
  ,PER_ORG_TREE_NODE POTN
   WHERE
   1 = 1
   AND POTN.TREE_CODE = 'OWWSC_ORG_TREE'
   AND HAOU1.ORGANIZATION_ID = POTN.PARENT_PK1_VALUE
   AND HAOU1.ATTRIBUTE2 = 'SECTION'
   AND ROWNUM = 1 START WITH POTN.PK1_START_VALUE = HAOUF.ORGANIZATION_ID CONNECT BY PRIOR POTN.PARENT_PK1_VALUE = POTN.PK1_START_VALUE) SECTION
,TO_CHAR(PAPF.START_DATE, 'DD-MON-YYYY','NLS_DATE_LANGUAGE = AMERICAN') DATE_OF_JOINING
,HAP.NAME POSITION
,PD.NAME DEPARTMENT
,PGF.GRADE_CODE GRADE_NAME
,NVL(AN.ANU_BAL,0) NET_BAL
,NVL(AN.CFW,0) CARRIED_LAST_YEAR
,NVL(AN.CURRENT_YEAR_ACC_BAL,0) CURRENT_YEAR_ACC_BAL
,NVL(ADJ.ADJUSMENTS,0) ADJUSMENTS	
,NVL(AD.DURATION,0) ANNUAL_LEAVE_TAKEN
,(NVL(LTY.CFW,0)+ NVL(LY.CFW,0))CARRIED_2
,NVL(LY.ANU_BAL,0) PREVIOUS_YEAR_BALANCE
,TO_CHAR(LTY.ACCRUAL_PERIOD , 'YYYY','NLS_DATE_LANGUAGE = AMERICAN') CARRIED_FROM 
,TO_CHAR(LY.ACCRUAL_PERIOD , 'YYYY','NLS_DATE_LANGUAGE = AMERICAN') CARRIED_PRE_FROM 
,TO_CHAR(AN.ACCRUAL_PERIOD , 'YYYY','NLS_DATE_LANGUAGE = AMERICAN') CURRENT_TO
,PCAK.SEGMENT4 COST_CENTER
,AD.NAME ENTITLEMENT
,' ' LEAVE_ENCASHMENT


FROM
PER_PERSONS                   PP
,PER_ALL_PEOPLE_F             PAPF
,PER_PERSON_NAMES_F           PPNF
,PER_ALL_ASSIGNMENTS_F        PAAF
,HR_ALL_POSITIONS_F_VL        HAP
,PER_DEPARTMENTS              PD
,HR_ALL_ORGANIZATION_UNITS_F  HAOUF
,PER_GRADES_F                 PGF
,PAY_COST_ALLOCATION_KEYFLEX  PCAK
,ANNUAL                       AN
,ADJUSYMENT                   ADJ
,ABSENCE_DETAILS              AD
,LAST_TWO_YEAR                LTY
,LAST_YEAR                    LY
WHERE PP.PERSON_ID                      = PAPF.PERSON_ID
AND PAPF.PERSON_ID						= PPNF.PERSON_ID
AND PAPF.PERSON_ID						= PAAF.PERSON_ID
AND PPNF.NAME_TYPE						= 'GLOBAL'
AND PAAF.ASSIGNMENT_STATUS_TYPE			= 'ACTIVE'
AND PAAF.ASSIGNMENT_TYPE				= 'E'
AND PAAF.PRIMARY_ASSIGNMENT_FLAG		= 'Y'
AND PAAF.POSITION_ID                    = HAP.POSITION_ID(+)
AND PAAF.ORGANIZATION_ID                = PD.ORGANIZATION_ID(+)
AND PAAF.ORGANIZATION_ID                = HAOUF.ORGANIZATION_ID(+)
AND PAAF.GRADE_ID                       = PGF.GRADE_ID(+)
AND HAOUF.COST_ALLOCATION_KEYFLEX_ID    = PCAK.COST_ALLOCATION_KEYFLEX_ID(+)
AND PAPF.PERSON_ID						= AN.PERSON_ID(+)
AND PAPF.PERSON_ID						= ADJ.PERSON_ID(+)
AND PAAF.PERSON_ID						= AD.PERSON_ID(+)
AND PAPF.PERSON_ID						= LTY.PERSON_ID(+)
AND PAPF.PERSON_ID						= LY.PERSON_ID(+)
AND TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
AND TRUNC(SYSDATE) BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
AND TRUNC(SYSDATE) BETWEEN PAAF.EFFECTIVE_START_DATE AND PAAF.EFFECTIVE_END_DATE
AND PAPF.PERSON_NUMBER                  = NVL(:P_EMP_NUM,PAPF.PERSON_NUMBER)
 -- AND PAPF.PERSON_NUMBER ='7314'


ORDER BY PAPF.PERSON_NUMBER

-- PARAMETERS

-- EMPLOYEE NUMBER
SELECT DISTINCT 
	-- PAPF.PERSON_NUMBER||' '||PPNF.LAST_NAME||','||PPNF.TITLE||' '||PPNF.FIRST_NAME||' '||PPNF.MIDDLE_NAMES||' '||PPNF.NAM_INFORMATION1 NAME,
PAPF.PERSON_NUMBER ||' '||PPNF.FULL_NAME NAME,
	PAPF.PERSON_NUMBER
	FROM 
	PER_ALL_PEOPLE_F PAPF
	,PER_PERSON_NAMES_F         PPNF
	,PER_ALL_ASSIGNMENTS_F      PAAF
	WHERE
	PAPF.PERSON_ID=PPNF.PERSON_ID
	AND PAPF.PERSON_ID          = PAAF.PERSON_ID
	AND  PAAF.ASSIGNMENT_STATUS_TYPE    = 'ACTIVE'
	AND  PAAF.ASSIGNMENT_TYPE           = 'E'
	AND  PAAF.PRIMARY_ASSIGNMENT_FLAG   = 'Y'
	AND TRUNC(SYSDATE) 				   BETWEEN TRUNC(PAPF.EFFECTIVE_START_DATE) AND TRUNC(PAPF.EFFECTIVE_END_DATE)
	 AND TRUNC(SYSDATE) 				   BETWEEN TRUNC(PPNF.EFFECTIVE_START_DATE) AND TRUNC(PPNF.EFFECTIVE_END_DATE)
	 AND TRUNC(SYSDATE)                    BETWEEN TRUNC(PAAF.EFFECTIVE_START_DATE) AND TRUNC(PAAF.EFFECTIVE_END_DATE)
	ORDER BY PAPF.PERSON_NUMBER