

/* EMPLOYEE LEAVE SUMMARY REPORT */

SELECT
ORG.STAFF_NUMBER
,ORG.STAFF_NAME
,ORG.POSITION
,ORG.DIRECTORATE
,ORG.DEPARTMENT
,ORG.SECTION
,ORG.SUB_SECTION
,LD.NATIONALITY
,ORG.DATE_OF_JOINING
,ORG.JOB
,LD.AFTER_NOON_HALF_DAY_ANNUAL_LEAVE
,LD.ANNUAL_LEAVE
,LD.ATTENDING_MEETING
,LD.EMERGENCY_LEAVE
,LD.EXCEPTIONAL_LEAVE
,LD.HAYA_TRANSFERRED_ANNUAL_LEAVE
,LD.PATIENT_ESCORT_LEAVE
,LD.SICK_LEAVE
,LD.TRAINING
,LD.WORKING_FROM_HOME
,LD.LAST_YEAR_CFW_ANNUAL
,LD.CURRENT_YEAR_LEAVE_ANNUAL
,(LD.LAST_YEAR_CFW_ANNUAL +LD.CURRENT_YEAR_LEAVE_ANNUAL) TOTAL_ELIGIBILITY_ANNUAL
,LD.ANNUAL_LEAVE_REMAINING
,LD.LAST_YEAR_CFW_COM
,LD.CURRENT_YEAR_LEAVE_COM
,(LD.LAST_YEAR_CFW_COM +LD.CURRENT_YEAR_LEAVE_COM) TOTAL_ELIGIBILITY_COM
,LD.COMPENSATED_LEAVE_BALANCE
,LD.TRANSFERRED_ANNUAL_LEAVE_REMAINING
,LD.ANNUAL_LEAVE_ADJUSTED
,LD.MORNING_HALF_DAY_ANNUAL_LEAVE
,LD.AWAY_DAY
,LD.COMPENSATED_LEAVE
,LD.EXAMINATION_LEAVE
,LD.DEATH_OF_RELATIVE
,LD.AFTER_NOON_HALF_DAY_LEAVE
,LD.MORNING_HALF_DAY_LEAVE
,LD.AFTER_NOON_HALF_DAY_SITE_VISIT
,LD.MORNING_HALF_DAY_SITE_VISIT
,LD.AFTER_NOON_HALF_DAY_COMPENSATED_LEAVE
,LD.MORNING_HALF_DAY_COMPENSATED_LEAVE
,LD.MARRIAGE_LEAVE
,LD.MOTHERHOOD_LEAVE
,LD.PATERNITY_LEAVE
,LD.MATERNITY_LEAVE
,LD.STUDY_LEAVE
,LD.SPECIAL_LEAVE
,LD.SHIFT_LEAVE
,LD.SITE_VISIT
,LD.OFFICIAL_MISSION
,LD.LOCAL_OFFICIAL_MISSION
,LD.WORK_INJURIES
,LD.COMPENSATED_LEAVE_SHIFT
,LD.TRANSFERRED_ANNUAL_LEAVE
,LD.UNPAID_LEAVE
,LD.WORKSHOP
,LD.AFTERNOON_HALFDAY_COMPENSATED_SHIFT
,LD.SICK_LEAVE_FULL_PAY
,LD.ABSENCE_UNPAID_LEAVE
,LD.HR_DEDUCTION_ANNUAL_LEAVE
,LD.MORNING_HALFDAY_COMPENSATED_SHIFT
,LD.WORK_FROM_HOME_SPECIAL_CASE
,LD.HAJJ_LEAVE
,LD.HR_DEDUCTION_TRANSFER_ANNUAL_LEAVE
,LD.HR_DEDUCTION_COMPENSATED_LEAVE
,LD.STUDY_LEAVE_UNPAID
,LD.SHARAKAH
,LD.AFTERNOON_HALFDAY_TRANSFER_ANNUAL
,LD.MORNING_HALFDAY_TRANSFER_ANNUAL
,LD.DEATH_OF_HUSBAND
-- ,ORG.P_DRILL_DOWN

FROM
(
(
SELECT DISTINCT
 PAPF.PERSON_ID
,PAPF.PERSON_NUMBER STAFF_NUMBER
,PPNF.FULL_NAME AS STAFF_NAME
,PPS.POSITION
,(
    SELECT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
      AND POTN.TREE_CODE = 'NWS_Org_Tree'
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Directorate'
      AND ROWNUM = 1 START WITH POTN.PK1_START_VALUE = HAOU.ORGANIZATION_ID CONNECT BY PRIOR POTN.PARENT_PK1_VALUE = POTN.PK1_START_VALUE
  ) DIRECTORATE
   ,(
    SELECT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
      AND POTN.TREE_CODE = 'NWS_Org_Tree'
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Department'
      AND ROWNUM = 1 START WITH POTN.PK1_START_VALUE = HAOU.ORGANIZATION_ID CONNECT BY PRIOR POTN.PARENT_PK1_VALUE = POTN.PK1_START_VALUE
  ) DEPARTMENT
   ,(
    SELECT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
      AND POTN.TREE_CODE = 'NWS_Org_Tree'
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Section'
      AND ROWNUM = 1 START WITH POTN.PK1_START_VALUE = HAOU.ORGANIZATION_ID CONNECT BY PRIOR POTN.PARENT_PK1_VALUE = POTN.PK1_START_VALUE
  ) SECTION
 ,(
    SELECT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
      AND POTN.TREE_CODE = 'NWS_Org_Tree'
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Sub-Section'
      AND ROWNUM = 1 START WITH POTN.PK1_START_VALUE = HAOU.ORGANIZATION_ID CONNECT BY PRIOR POTN.PARENT_PK1_VALUE = POTN.PK1_START_VALUE
  ) SUB_SECTION
  ,TO_CHAR(PAPF.START_DATE ,'DD-Mon-YYYY','NLS_DATE_LANGUAGE = AMERICAN') DATE_OF_JOINING
,PJFV.NAME JOB

 FROM 
 PER_ALL_PEOPLE_F           PAPF
,PER_PERSON_NAMES_F         PPNF
,PER_ALL_ASSIGNMENTS_F      PAAF
,PER_JOBS_F_VL              PJFV
,HR_ALL_ORGANIZATION_UNITS  HAOU
,(
SELECT HAPF.POSITION_ID,
HAPF.NAME POSITION,
HAPF.POSITION_CODE POSTION_CODE
FROM  HR_ALL_POSITIONS          HAPF
WHERE 1=1
AND TRUNC(SYSDATE) BETWEEN TRUNC(NVL(HAPF.EFFECTIVE_START_DATE,SYSDATE)) AND TRUNC(NVL(HAPF.EFFECTIVE_END_DATE,SYSDATE))) PPS

WHERE PAPF.PERSON_ID          = PPNF.PERSON_ID
 AND  PAPF.PERSON_ID          = PAAF.PERSON_ID(+)
 AND  PAAF.JOB_ID             = PJFV.JOB_ID(+)
 AND  PAAF.POSITION_ID        = PPS.POSITION_ID(+)
 AND  PAAF.ORGANIZATION_ID    = HAOU.ORGANIZATION_ID(+)
 
 AND  PPNF.NAME_TYPE                 ='GLOBAL'
 AND  PAAF.ASSIGNMENT_STATUS_TYPE    = 'ACTIVE'
 AND  PAAF.ASSIGNMENT_TYPE           = 'E'
 AND  PAAF.PRIMARY_ASSIGNMENT_FLAG   = 'Y'
 AND TRUNC(SYSDATE) 				   BETWEEN TRUNC(PAPF.EFFECTIVE_START_DATE) AND TRUNC(PAPF.EFFECTIVE_END_DATE)
 AND TRUNC(SYSDATE) 				   BETWEEN TRUNC(PPNF.EFFECTIVE_START_DATE) AND TRUNC(PPNF.EFFECTIVE_END_DATE)
 AND TRUNC(SYSDATE)                    BETWEEN TRUNC(PAAF.EFFECTIVE_START_DATE) AND TRUNC(PAAF.EFFECTIVE_END_DATE)
 AND :P_DRILL_DOWN='Yes'
 
 )
 
 UNION
 
 (
 SELECT DISTINCT
 PAPF.PERSON_ID
,PAPF.PERSON_NUMBER STAFF_NUMBER
,PPNF.FULL_NAME AS STAFF_NAME
,PPS.POSITION
,(
    SELECT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
      AND POTN.TREE_CODE = 'NWS_Org_Tree'
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Directorate'
      AND POTN.PK1_START_VALUE = HAOU.ORGANIZATION_ID
  ) DIRECTORATE
   ,(
    SELECT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
      AND POTN.TREE_CODE = 'NWS_Org_Tree'
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Department'
     AND POTN.PK1_START_VALUE = HAOU.ORGANIZATION_ID
  ) DEPARTMENT
   ,(
    SELECT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
      AND POTN.TREE_CODE = 'NWS_Org_Tree'
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Section'
     AND POTN.PK1_START_VALUE = HAOU.ORGANIZATION_ID
  ) SECTION
 ,(
    SELECT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
      AND POTN.TREE_CODE = 'NWS_Org_Tree'
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Sub-Section'
      AND POTN.PK1_START_VALUE = HAOU.ORGANIZATION_ID
  ) SUB_SECTION
  ,TO_CHAR(PAPF.START_DATE ,'DD-Mon-YYYY','NLS_DATE_LANGUAGE = AMERICAN') DATE_OF_JOINING
,PJFV.NAME JOB

 FROM 
 PER_ALL_PEOPLE_F           PAPF
,PER_PERSON_NAMES_F         PPNF
,PER_ALL_ASSIGNMENTS_F      PAAF
,PER_JOBS_F_VL              PJFV
,HR_ALL_ORGANIZATION_UNITS  HAOU
,(
SELECT HAPF.POSITION_ID,
HAPF.NAME POSITION,
HAPF.POSITION_CODE POSTION_CODE
FROM  HR_ALL_POSITIONS          HAPF
WHERE 1=1
AND TRUNC(SYSDATE) BETWEEN TRUNC(NVL(HAPF.EFFECTIVE_START_DATE,SYSDATE)) AND TRUNC(NVL(HAPF.EFFECTIVE_END_DATE,SYSDATE))) PPS

WHERE PAPF.PERSON_ID          = PPNF.PERSON_ID
 AND  PAPF.PERSON_ID          = PAAF.PERSON_ID(+)
 AND  PAAF.JOB_ID             = PJFV.JOB_ID(+)
 AND  PAAF.POSITION_ID        = PPS.POSITION_ID(+)
 AND  PAAF.ORGANIZATION_ID    = HAOU.ORGANIZATION_ID(+)
 
 AND  PPNF.NAME_TYPE                 ='GLOBAL'
 AND  PAAF.ASSIGNMENT_STATUS_TYPE    = 'ACTIVE'
 AND  PAAF.ASSIGNMENT_TYPE           = 'E'
 AND  PAAF.PRIMARY_ASSIGNMENT_FLAG   = 'Y'
 AND TRUNC(SYSDATE) 				   BETWEEN TRUNC(PAPF.EFFECTIVE_START_DATE) AND TRUNC(PAPF.EFFECTIVE_END_DATE)
 AND TRUNC(SYSDATE) 				   BETWEEN TRUNC(PPNF.EFFECTIVE_START_DATE) AND TRUNC(PPNF.EFFECTIVE_END_DATE)
 AND TRUNC(SYSDATE)                    BETWEEN TRUNC(PAAF.EFFECTIVE_START_DATE) AND TRUNC(PAAF.EFFECTIVE_END_DATE)
 AND :P_DRILL_DOWN='No'
 )
 ) ORG

,(
WITH NATION AS 
(SELECT HLN.MEANING NAME,PEC.PERSON_ID
 FROM  PER_CITIZENSHIPS PEC, 
 FND_LOOKUP_VALUES  HLN 
 WHERE 
      PEC.LEGISLATION_CODE = HLN.LOOKUP_CODE(+) 
 AND   HLN.LOOKUP_TYPE   = 'NATIONALITY'
 AND 	HLN.LANGUAGE = 'US')
 
,ABSENCE_DETAILS AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME = 'After Noon HalfDay Transferred Annual Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS1 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Annual Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS2 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Attending Meeting'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS3 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Emergency Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS4 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Exception Leave (Sporting & Culture Event)'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS5 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Haya Transferred Annual leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS6 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Patient Escort Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS7 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Sick Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS8 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Training'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS9 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Working From Home'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS10 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Morning HalfDay Transferred Annual Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS11 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Away Day'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS12 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Compensated Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS13 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Examination Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS14 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Death Of Relative'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS15 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='After Noon Half Day Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS16 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Morning Half Day Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS17 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='After Noon Half Day Site Visit'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS18 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Morning Half Day Site Visit'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS19 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='After Noon Half Day Compensated Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS20 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Morning Half Day Compensated Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS21 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Marriage Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS22 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Motherhood Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS23 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Paternity Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS24 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Maternity Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS25 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Study Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS26 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Special Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS27 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Shift Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS28 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Site Visit'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS29 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Official Mission'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS30 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Local Official Mission'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS31 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Work Injuries'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS32 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Compensated Leave - Shift'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS33 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Transferred Annual Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS34 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Unpaid Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS35 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Workshop'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS36 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='After Noon HalfDay Compensated - Shift'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS37 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Sick Leave Full Pay'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)

,ABSENCE_DETAILS38 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Absence (Unpaid Leave)'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS39 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='HR Deduction Annual Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS40 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Morning HalfDay Compensated - Shift'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS41 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Work From Home – Special Case'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS42 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Hajj Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS43 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='HR Deduction Transfer Annual Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS44 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='HR Deduction Compensated Leave'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS45 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Study Leave - Unpaid'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS46 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Sharakah'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS47 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='After Noon Half Day Transfer Annual'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS48 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Morning Half Day Transfer Annual'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,ABSENCE_DETAILS49 AS
		(
		SELECT
			APAE.PERSON_ID,
			SUM(APAE.DURATION) DURATION 
		FROM
			ANC_PER_ABS_ENTRIES APAE,
			ANC_ABSENCE_TYPES_VL AATV
		WHERE  1 = 1
			AND APAE.ABSENCE_TYPE_ID 	 = AATV.ABSENCE_TYPE_ID
			-- AND APAE.APPROVAL_STATUS_CD	= 'APPROVED'
			AND APAE.ABSENCE_STATUS_CD	<> 'ORA_WITHDRAWN'
			AND AATV.NAME ='Death of Husband'
			AND TRUNC(sysdate) BETWEEN TRUNC(AATV.EFFECTIVE_START_DATE) AND TRUNC(AATV.EFFECTIVE_END_DATE)
			AND (TO_CHAR(APAE.END_DATE,'YYYY') IN (:P_PERIOD_Y) OR 'ALL' IN((:P_PERIOD_Y) || 'ALL'))
		GROUP BY APAE.PERSON_ID
		)
		
,PLANS_DETAILS AS
(SELECT 	 APAE.END_BAL ANU_BAL
			,APAE.PERSON_ID
			,APAE.PLAN_ID
			,APAE.BEGIN_BAL CFW
			,APAE.ACCRUED CURRENT_YEAR
            			
	FROM 
	 ANC_PER_ACCRUAL_ENTRIES APAE
	,ANC_ABSENCE_PLANS_VL AAPV
  WHERE APAE.PLAN_ID = AAPV.ABSENCE_PLAN_ID(+)
  AND AAPV.NAME = 'Annual Leave'
  AND APAE.ACCRUAL_PERIOD  =(SELECT MAX (APA.ACCRUAL_PERIOD)
                           FROM ANC_PER_ACCRUAL_ENTRIES APA
                           WHERE APAE.PERSON_ID = APA.PERSON_ID
                           AND APA.PLAN_ID  = APAE.PLAN_ID
						   
						   AND TO_CHAR(APA.ACCRUAL_PERIOD,'YYYY') <= TO_CHAR(SYSDATE,'YYYY')
                           )
)

,PLANS_DETAILS1 AS
(SELECT 	 APAE.END_BAL COM_BAL
			,APAE.PERSON_ID
			,APAE.PLAN_ID
			,APAE.BEGIN_BAL CFW
			,APAE.ACCRUED CURRENT_YEAR
            			
	FROM 
	 ANC_PER_ACCRUAL_ENTRIES APAE
	,ANC_ABSENCE_PLANS_VL AAPV
  WHERE APAE.PLAN_ID = AAPV.ABSENCE_PLAN_ID(+)
  AND AAPV.NAME = 'Compensated Leave'
  AND APAE.ACCRUAL_PERIOD  =(SELECT MAX (APA.ACCRUAL_PERIOD)
                           FROM ANC_PER_ACCRUAL_ENTRIES APA
                           WHERE APAE.PERSON_ID = APA.PERSON_ID
                           AND APA.PLAN_ID  = APAE.PLAN_ID
						   
						   AND TO_CHAR(APA.ACCRUAL_PERIOD,'YYYY') <= TO_CHAR(SYSDATE,'YYYY')
                           )
)

,PLANS_DETAILS2 AS
(SELECT 	 APAE.END_BAL TRANS_BAL
			,APAE.PERSON_ID
			,APAE.PLAN_ID
			,APAE.BEGIN_BAL CFW
			,APAE.ACCRUED CURRENT_YEAR
            			
	FROM 
	 ANC_PER_ACCRUAL_ENTRIES APAE
	,ANC_ABSENCE_PLANS_VL AAPV
  WHERE APAE.PLAN_ID = AAPV.ABSENCE_PLAN_ID(+)
  AND AAPV.NAME = 'Transferred Annual Leave'
  AND APAE.ACCRUAL_PERIOD  =(SELECT MAX (APA.ACCRUAL_PERIOD)
                           FROM ANC_PER_ACCRUAL_ENTRIES APA
                           WHERE APAE.PERSON_ID = APA.PERSON_ID
                           AND APA.PLAN_ID  = APAE.PLAN_ID
						   
						   AND TO_CHAR(APA.ACCRUAL_PERIOD,'YYYY') <= TO_CHAR(SYSDATE,'YYYY')
                           )
)

SELECT
PAPF1.PERSON_ID
,PAPF1.PERSON_NUMBER
,NA.NAME NATIONALITY
,NVL(ABSN_DTL.DURATION,0) AFTER_NOON_HALF_DAY_ANNUAL_LEAVE
,NVL(ABSN_DTL1.DURATION,0) ANNUAL_LEAVE
,NVL(ABSN_DTL2.DURATION,0) ATTENDING_MEETING
,NVL(ABSN_DTL3.DURATION,0) EMERGENCY_LEAVE
,NVL(ABSN_DTL4.DURATION,0) EXCEPTIONAL_LEAVE
,NVL(ABSN_DTL5.DURATION,0) HAYA_TRANSFERRED_ANNUAL_LEAVE
,NVL(ABSN_DTL6.DURATION,0) PATIENT_ESCORT_LEAVE
,NVL(ABSN_DTL7.DURATION,0) SICK_LEAVE
,NVL(ABSN_DTL8.DURATION,0) TRAINING
,NVL(ABSN_DTL9.DURATION,0) WORKING_FROM_HOME
,NVL(ABSN_DTL10.DURATION,0) MORNING_HALF_DAY_ANNUAL_LEAVE
,NVL(ABSN_DTL11.DURATION,0) AWAY_DAY
,NVL(ABSN_DTL12.DURATION,0) COMPENSATED_LEAVE
,NVL(ABSN_DTL13.DURATION,0) EXAMINATION_LEAVE
,NVL(ABSN_DTL14.DURATION,0) DEATH_OF_RELATIVE
,NVL(ABSN_DTL15.DURATION,0) AFTER_NOON_HALF_DAY_LEAVE
,NVL(ABSN_DTL16.DURATION,0) MORNING_HALF_DAY_LEAVE
,NVL(ABSN_DTL17.DURATION,0) AFTER_NOON_HALF_DAY_SITE_VISIT
,NVL(ABSN_DTL18.DURATION,0) MORNING_HALF_DAY_SITE_VISIT
,NVL(ABSN_DTL19.DURATION,0) AFTER_NOON_HALF_DAY_COMPENSATED_LEAVE
,NVL(ABSN_DTL20.DURATION,0) MORNING_HALF_DAY_COMPENSATED_LEAVE
,NVL(ABSN_DTL21.DURATION,0) MARRIAGE_LEAVE
,NVL(ABSN_DTL22.DURATION,0) MOTHERHOOD_LEAVE
,NVL(ABSN_DTL23.DURATION,0) PATERNITY_LEAVE
,NVL(ABSN_DTL24.DURATION,0) MATERNITY_LEAVE
,NVL(ABSN_DTL25.DURATION,0) STUDY_LEAVE
,NVL(ABSN_DTL26.DURATION,0) SPECIAL_LEAVE
,NVL(ABSN_DTL27.DURATION,0) SHIFT_LEAVE
,NVL(ABSN_DTL28.DURATION,0) SITE_VISIT
,NVL(ABSN_DTL29.DURATION,0) OFFICIAL_MISSION
,NVL(ABSN_DTL30.DURATION,0) LOCAL_OFFICIAL_MISSION
,NVL(ABSN_DTL31.DURATION,0) WORK_INJURIES
,NVL(ABSN_DTL32.DURATION,0) COMPENSATED_LEAVE_SHIFT
,NVL(ABSN_DTL33.DURATION,0) TRANSFERRED_ANNUAL_LEAVE
,NVL(ABSN_DTL34.DURATION,0) UNPAID_LEAVE
,NVL(ABSN_DTL35.DURATION,0) WORKSHOP
,NVL(ABSN_DTL36.DURATION,0) AFTERNOON_HALFDAY_COMPENSATED_SHIFT
,NVL(ABSN_DTL37.DURATION,0) SICK_LEAVE_FULL_PAY
,NVL(ABSN_DTL38.DURATION,0) ABSENCE_UNPAID_LEAVE
,NVL(ABSN_DTL39.DURATION,0) HR_DEDUCTION_ANNUAL_LEAVE
,NVL(ABSN_DTL40.DURATION,0) MORNING_HALFDAY_COMPENSATED_SHIFT
,NVL(ABSN_DTL41.DURATION,0) WORK_FROM_HOME_SPECIAL_CASE
,NVL(ABSN_DTL42.DURATION,0) HAJJ_LEAVE
,NVL(ABSN_DTL43.DURATION,0) HR_DEDUCTION_TRANSFER_ANNUAL_LEAVE
,NVL(ABSN_DTL44.DURATION,0) HR_DEDUCTION_COMPENSATED_LEAVE
,NVL(ABSN_DTL44.DURATION,0) STUDY_LEAVE_UNPAID
,NVL(ABSN_DTL46.DURATION,0) SHARAKAH
,NVL(ABSN_DTL47.DURATION,0) AFTERNOON_HALFDAY_TRANSFER_ANNUAL
,NVL(ABSN_DTL48.DURATION,0) MORNING_HALFDAY_TRANSFER_ANNUAL
,NVL(ABSN_DTL49.DURATION,0) DEATH_OF_HUSBAND
,NVL(PD.ANU_BAL,0)  ANNUAL_LEAVE_REMAINING
,NVL(PD.CFW,0) LAST_YEAR_CFW_ANNUAL
,NVL(PD.CURRENT_YEAR,0) CURRENT_YEAR_LEAVE_ANNUAL	
,NVL(PD1.COM_BAL ,0) COMPENSATED_LEAVE_BALANCE
,NVL(PD1.CFW,0) LAST_YEAR_CFW_COM
,NVL(PD1.CURRENT_YEAR,0) CURRENT_YEAR_LEAVE_COM
,NVL(PD2.TRANS_BAL,0) TRANSFERRED_ANNUAL_LEAVE_REMAINING
,NVL(ADJ.ADJUSMENTS,0) ANNUAL_LEAVE_ADJUSTED


FROM
PER_ALL_PEOPLE_F           PAPF1
,NATION                     NA
,ABSENCE_DETAILS 		    ABSN_DTL
,ABSENCE_DETAILS1 		    ABSN_DTL1
,ABSENCE_DETAILS2 		    ABSN_DTL2
,ABSENCE_DETAILS3 		    ABSN_DTL3
,ABSENCE_DETAILS4 		    ABSN_DTL4
,ABSENCE_DETAILS5 		    ABSN_DTL5
,ABSENCE_DETAILS6 		    ABSN_DTL6
,ABSENCE_DETAILS7 		    ABSN_DTL7
,ABSENCE_DETAILS8 		    ABSN_DTL8
,ABSENCE_DETAILS9 		    ABSN_DTL9
,ABSENCE_DETAILS10 		    ABSN_DTL10
,ABSENCE_DETAILS11		    ABSN_DTL11
,ABSENCE_DETAILS12		    ABSN_DTL12
,ABSENCE_DETAILS13		    ABSN_DTL13
,ABSENCE_DETAILS14		    ABSN_DTL14
,ABSENCE_DETAILS15		    ABSN_DTL15
,ABSENCE_DETAILS16		    ABSN_DTL16
,ABSENCE_DETAILS17		    ABSN_DTL17
,ABSENCE_DETAILS18		    ABSN_DTL18
,ABSENCE_DETAILS19		    ABSN_DTL19
,ABSENCE_DETAILS20		    ABSN_DTL20
,ABSENCE_DETAILS21		    ABSN_DTL21
,ABSENCE_DETAILS22		    ABSN_DTL22
,ABSENCE_DETAILS23		    ABSN_DTL23
,ABSENCE_DETAILS24		    ABSN_DTL24
,ABSENCE_DETAILS25		    ABSN_DTL25
,ABSENCE_DETAILS26		    ABSN_DTL26
,ABSENCE_DETAILS27		    ABSN_DTL27
,ABSENCE_DETAILS28		    ABSN_DTL28
,ABSENCE_DETAILS29		    ABSN_DTL29
,ABSENCE_DETAILS30		    ABSN_DTL30
,ABSENCE_DETAILS31		    ABSN_DTL31
,ABSENCE_DETAILS32		    ABSN_DTL32
,ABSENCE_DETAILS33		    ABSN_DTL33
,ABSENCE_DETAILS34		    ABSN_DTL34
,ABSENCE_DETAILS35		    ABSN_DTL35
,ABSENCE_DETAILS36		    ABSN_DTL36
,ABSENCE_DETAILS37		    ABSN_DTL37
,ABSENCE_DETAILS38		    ABSN_DTL38
,ABSENCE_DETAILS39		    ABSN_DTL39
,ABSENCE_DETAILS40		    ABSN_DTL40
,ABSENCE_DETAILS41		    ABSN_DTL41
,ABSENCE_DETAILS42		    ABSN_DTL42
,ABSENCE_DETAILS43		    ABSN_DTL43
,ABSENCE_DETAILS44		    ABSN_DTL44
,ABSENCE_DETAILS45		    ABSN_DTL45
,ABSENCE_DETAILS46		    ABSN_DTL46
,ABSENCE_DETAILS47		    ABSN_DTL47
,ABSENCE_DETAILS48		    ABSN_DTL48
,ABSENCE_DETAILS49		    ABSN_DTL49
,PLANS_DETAILS              PD
,PLANS_DETAILS1             PD1
,PLANS_DETAILS2             PD2
,(SELECT 
APAED1.PERSON_ID,
NVL(F.MEANING,'Adjustment') ADJUSTMENT_REASON,
SUM(APAED1.VALUE) ADJUSMENTS

FROM
ANC_PER_ACRL_ENTRY_DTLS APAED1,
ANC_ABSENCE_PLANS_VL      AAPV,
HCM_LOOKUPS F
WHERE 1=1
AND APAED1.TYPE = 'ADJOTH'
-- AND APAED1.SOURCE = 'ANC'
AND APAED1.VOIDED_ACRL <> 'Y'
AND APAED1.ADJUSTMENT_REASON		=F.LOOKUP_CODE(+)
AND APAED1.PL_ID 				  	= AAPV.ABSENCE_PLAN_ID
AND TRUNC(SYSDATE) BETWEEN TRUNC(AAPV.EFFECTIVE_START_DATE) AND TRUNC(AAPV.EFFECTIVE_END_DATE)
AND AAPV.NAME						IN ('Annual Leave')
AND F.LOOKUP_TYPE(+)='ANC_ABS_PLAN_OTHER_REASONS'
GROUP BY
APAED1.PERSON_ID,
F.MEANING
)ADJ


WHERE  PAPF1.PERSON_ID          = NA.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL1.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL2.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL3.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL4.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL5.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL6.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL7.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL8.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL9.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL10.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL11.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL12.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL13.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL14.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL15.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL16.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL17.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL18.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL19.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL20.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL21.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL22.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL23.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL24.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL25.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL26.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL27.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL28.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL29.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL30.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL31.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL32.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL33.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL34.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL35.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL36.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL37.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL38.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL39.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL40.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL41.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL42.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL43.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL44.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL45.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL46.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL47.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL48.PERSON_ID(+)
 AND  PAPF1.PERSON_ID          = ABSN_DTL49.PERSON_ID(+)
 AND PAPF1.PERSON_ID           = PD.PERSON_ID(+)
 AND PAPF1.PERSON_ID           = PD1.PERSON_ID(+)
 AND PAPF1.PERSON_ID           = PD2.PERSON_ID(+)
 AND PAPF1.PERSON_ID 		  = ADJ.PERSON_ID(+)
-- AND PAPF1.PERSON_NUMBER='7314'

) LD
WHERE 1=1
AND ORG.PERSON_ID = LD.PERSON_ID
AND (STAFF_NUMBER IN (:P_PERSON_NUM) OR 'ALL' IN (:P_PERSON_NUM || 'ALL'))
AND (DIRECTORATE IN (:P_DIRECTORATE) OR 'ALL' IN (:P_DIRECTORATE || 'ALL'))
AND (DEPARTMENT IN (:P_DEPARTMENT) OR 'ALL' IN (:P_DEPARTMENT || 'ALL'))
AND (SECTION IN (:P_SECTION) OR 'ALL' IN (:P_SECTION || 'ALL'))
AND (SUB_SECTION IN (:P_SUB) OR 'ALL' IN (:P_SUB || 'ALL'))

ORDER BY TO_NUMBER(STAFF_NUMBER)

/* DATA SET 2 */

SELECT TO_CHAR(SYSDATE,'DD-MM-YYYY','NLS_DATE_LANGUAGE = AMERICAN') SDATE FROM DUAL

-- PARAMETERS

-- EMPLOYEE NUMBER
SELECT DISTINCT 
PAPF.PERSON_NUMBER ||' '||PPNF.FULL_NAME NAME,
PAPF.PERSON_NUMBER 
FROM 
PER_ALL_PEOPLE_F PAPF
,PER_PERSON_NAMES_F         PPNF
,PER_ALL_ASSIGNMENTS_F      PAAF
WHERE
PAPF.PERSON_ID=PPNF.PERSON_ID
AND PAPF.PERSON_ID          = PAAF.PERSON_ID
AND  PAAF.ASSIGNMENT_STATUS_TYPE    = 'ACTIVE'
AND  PAAF.ASSIGNMENT_TYPE           = 'E'
AND  PAAF.PRIMARY_ASSIGNMENT_FLAG   = 'Y'
AND TRUNC(SYSDATE) 				   BETWEEN TRUNC(PAPF.EFFECTIVE_START_DATE) AND TRUNC(PAPF.EFFECTIVE_END_DATE)
 AND TRUNC(SYSDATE) 				   BETWEEN TRUNC(PPNF.EFFECTIVE_START_DATE) AND TRUNC(PPNF.EFFECTIVE_END_DATE)
 AND TRUNC(SYSDATE)                    BETWEEN TRUNC(PAAF.EFFECTIVE_START_DATE) AND TRUNC(PAAF.EFFECTIVE_END_DATE)
ORDER BY PAPF.PERSON_NUMBER

-- DEPARTMENT

SELECT DISTINCT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
 
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Department'
AND POTN.TREE_CODE = 'NWS_Org_Tree'

ORDER BY NAME

-- DIRECTORATE

SELECT DISTINCT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
 
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Directorate'
AND POTN.TREE_CODE = 'NWS_Org_Tree'

ORDER BY NAME

-- SECTION

SELECT DISTINCT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
 
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Section'
AND POTN.TREE_CODE = 'NWS_Org_Tree'

ORDER BY NAME

-- SUB-SECTION

SELECT DISTINCT
      haou1.name
    FROM
      HR_ALL_ORGANIZATION_UNITS HAOU1,
      PER_ORG_TREE_NODE POTN
    WHERE
      1 = 1
 
      AND HAOU1.ORGANIZATION_ID = POTN.PK1_START_VALUE
      AND HAOU1.ATTRIBUTE2 = 'Sub-Section'
AND POTN.TREE_CODE = 'NWS_Org_Tree'

ORDER BY NAME

--PERIOD
SELECT DISTINCT TO_CHAR(APAE.END_DATE,'YYYY') P_YEAR
FROM ANC_PER_ABS_ENTRIES APAE

ORDER BY TO_CHAR(APAE.END_DATE,'YYYY') desc

-- DRILL DOWN
SELECT 'Yes' FROM DUAL
UNION
SELECT 'No' FROM DUAL